stages:
  - install
  - build
  - quality
  - clean
  - deploy

linting:
  stage: quality
  tags:
    - test
  script:
    - npm run lint

test:
  stage: quality
  tags:
    - test
  script:
    -  npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

install:
  stage: install
  tags:
    - test
  script:
    - npm install
  artifacts:
    name: "artifacts"
    expire_in: 1 week
    untracked: true
    paths:
      - node_modules/

build:
  stage: build
  tags:
    - test
  script:
    - CI=false npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - .nuxt
  dependencies:
    - install

remove_container:
  stage: clean
  tags:
    - deploy
  script:
    - sudo docker stop ocs-server
  allow_failure: true
  dependencies:
    - build
    - install
    - linting
    - test
  
deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - mkdir data
    - mv $SSL_CERT ./data/ssl.cert
    - mv $SSL_KEY ./data/ssl.key
    - sudo docker build -t  ocs-server .
    - sudo docker run -p 3001:3001 -d --rm --name ocs-server ocs-server npm start
  dependencies:
    - clean
