stages:
  - install
  - build
  - quality
  - deploy

linting:
  stage: quality
  tags:
    - test
  script:
    - npm run lint

test:
  stage: quality
  tags:
    - test
  script:
    -  npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

install:
  stage: install
  tags:
    - test
  script:
    - npm install
  artifacts:
    name: "artifacts"
    expire_in: 1 week
    untracked: true
    paths:
      - node_modules/

build:
  stage: build
  tags:
    - test
  script:
    - CI=false npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - .nuxt
  dependencies:
    - install

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - ls -la
    - docker build -t ocs-server .
    - docker run -p 3001:3001 ocs-server npm start
  dependencies:
    - build
    - install
    - linting
    - test
