stages:
  - install
  - build
  - quality
  - deploy

linting:
  stage: quality
  tags:
    - test
  script:
    - npm run lint

test:
  stage: quality
  tags:
    - test
  script:
    -  npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

install:
  stage: install
  tags:
    - test
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    paths:
      - node_modules/

build:
  stage: build
  tags:
    - test
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - dist
  dependencies:
    - install

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - docker build -t ocs-server dockerfile
    - docker run ocs-server
  dependencies:
    - build
    - install
    - linting
    - test
