stages:
  - install
  - build
  - quality
  - deploy

linting:
  stage: quality
  script:
    - npm run lint

test:
  stage: quality
  script:
    -  npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 30 mins
  dependencies:
    - install

deploy:
  stage: deploy
  script:
    - npm start
  dependencies:
    - linting
    - test