const setup = require('./setup/setup.service')
const logger = require('./logger/logger.service')
const users = require('./users/users.service')
const authentication = require('./authentication/authentication.service')
const subnets = require('./subnets/subnets.service')
const devices = require('./devices/devices.service')
const devicesDps = require('./devicesDps/devicesDps.service')
//  const groups = require('./groups/groups.service')
//  const rules = require('./rules/rules.service')
const images = require('./images/images.service')
const applications = require('./applications/applications.service')
const files = require('./files/files.service')
const locations = require('./locations/locations.service')

module.exports = function (app) {
  app.configure(setup)
  app.configure(logger)
  app.configure(users)
  app.configure(authentication)
  app.configure(subnets)
  app.configure(devices)
  app.configure(devicesDps)
  //  app.configure(groups)
  //  app.configure(rules)
  app.configure(images)
  app.configure(applications)
  app.configure(files)
  app.configure(locations)
}
